server:
  port: 3344
spring:
  application:
    name: microsservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/13752082981/microsservicecloud-config.git #github上的仓库地址
